/**
 * ISO 3166-1 country codes (Phase 7). MusicBrainz hands out alpha-2 codes
 * while the bundled world-atlas TopoJSON carries ISO numeric feature ids and
 * English names only - this table bridges the two and supplies display names
 * when only a code is known.
 */

export interface IsoCountry {
	/** ISO 3166-1 numeric code, matching world-atlas feature ids. */
	numeric: string;
	name: string;
}

export const ISO_COUNTRIES: Readonly<Record<string, IsoCountry>> = {
	AC: { numeric: "", name: "Ascension Island" },
	AD: { numeric: "020", name: "Andorra" },
	AE: { numeric: "784", name: "United Arab Emirates" },
	AF: { numeric: "004", name: "Afghanistan" },
	AG: { numeric: "028", name: "Antigua and Barbuda" },
	AI: { numeric: "660", name: "Anguilla" },
	AL: { numeric: "008", name: "Albania" },
	AM: { numeric: "051", name: "Armenia" },
	AO: { numeric: "024", name: "Angola" },
	AQ: { numeric: "010", name: "Antarctica" },
	AR: { numeric: "032", name: "Argentina" },
	AS: { numeric: "016", name: "American Samoa" },
	AT: { numeric: "040", name: "Austria" },
	AU: { numeric: "036", name: "Australia" },
	AW: { numeric: "533", name: "Aruba" },
	AX: { numeric: "248", name: "Åland Islands" },
	AZ: { numeric: "031", name: "Azerbaijan" },
	BA: { numeric: "070", name: "Bosnia and Herzegovina" },
	BB: { numeric: "052", name: "Barbados" },
	BD: { numeric: "050", name: "Bangladesh" },
	BE: { numeric: "056", name: "Belgium" },
	BF: { numeric: "854", name: "Burkina Faso" },
	BG: { numeric: "100", name: "Bulgaria" },
	BH: { numeric: "048", name: "Bahrain" },
	BI: { numeric: "108", name: "Burundi" },
	BJ: { numeric: "204", name: "Benin" },
	BL: { numeric: "652", name: "Saint Barthélemy" },
	BM: { numeric: "060", name: "Bermuda" },
	BN: { numeric: "096", name: "Brunei" },
	BO: { numeric: "068", name: "Bolivia" },
	BQ: { numeric: "535", name: "Bonaire, Sint Eustatius and Saba" },
	BR: { numeric: "076", name: "Brazil" },
	BS: { numeric: "044", name: "Bahamas" },
	BT: { numeric: "064", name: "Bhutan" },
	BV: { numeric: "074", name: "Bouvet Island" },
	BW: { numeric: "072", name: "Botswana" },
	BY: { numeric: "112", name: "Belarus" },
	BZ: { numeric: "084", name: "Belize" },
	CA: { numeric: "124", name: "Canada" },
	CC: { numeric: "166", name: "Cocos (Keeling) Islands" },
	CD: { numeric: "180", name: "DR Congo" },
	CF: { numeric: "140", name: "Central African Republic" },
	CG: { numeric: "178", name: "Congo" },
	CH: { numeric: "756", name: "Switzerland" },
	CI: { numeric: "384", name: "Côte d'Ivoire" },
	CK: { numeric: "184", name: "Cook Islands" },
	CL: { numeric: "152", name: "Chile" },
	CM: { numeric: "120", name: "Cameroon" },
	CN: { numeric: "156", name: "China" },
	CO: { numeric: "170", name: "Colombia" },
	CR: { numeric: "188", name: "Costa Rica" },
	CU: { numeric: "192", name: "Cuba" },
	CV: { numeric: "132", name: "Cabo Verde" },
	CW: { numeric: "531", name: "Curaçao" },
	CX: { numeric: "162", name: "Christmas Island" },
	CY: { numeric: "196", name: "Cyprus" },
	CZ: { numeric: "203", name: "Czechia" },
	DE: { numeric: "276", name: "Germany" },
	DJ: { numeric: "262", name: "Djibouti" },
	DK: { numeric: "208", name: "Denmark" },
	DM: { numeric: "212", name: "Dominica" },
	DO: { numeric: "214", name: "Dominican Republic" },
	DZ: { numeric: "012", name: "Algeria" },
	EC: { numeric: "218", name: "Ecuador" },
	EE: { numeric: "233", name: "Estonia" },
	EG: { numeric: "818", name: "Egypt" },
	EH: { numeric: "732", name: "Western Sahara" },
	ER: { numeric: "232", name: "Eritrea" },
	ES: { numeric: "724", name: "Spain" },
	ET: { numeric: "231", name: "Ethiopia" },
	FI: { numeric: "246", name: "Finland" },
	FJ: { numeric: "242", name: "Fiji" },
	FK: { numeric: "238", name: "Falkland Islands" },
	FM: { numeric: "583", name: "Micronesia" },
	FO: { numeric: "234", name: "Faroe Islands" },
	FR: { numeric: "250", name: "France" },
	GA: { numeric: "266", name: "Gabon" },
	GB: { numeric: "826", name: "United Kingdom" },
	GD: { numeric: "308", name: "Grenada" },
	GE: { numeric: "268", name: "Georgia" },
	GF: { numeric: "254", name: "French Guiana" },
	GG: { numeric: "831", name: "Guernsey" },
	GH: { numeric: "288", name: "Ghana" },
	GI: { numeric: "292", name: "Gibraltar" },
	GL: { numeric: "304", name: "Greenland" },
	GM: { numeric: "270", name: "Gambia" },
	GN: { numeric: "324", name: "Guinea" },
	GP: { numeric: "312", name: "Guadeloupe" },
	GQ: { numeric: "226", name: "Equatorial Guinea" },
	GR: { numeric: "300", name: "Greece" },
	GS: { numeric: "239", name: "South Georgia and the South Sandwich Islands" },
	GT: { numeric: "320", name: "Guatemala" },
	GU: { numeric: "316", name: "Guam" },
	GW: { numeric: "624", name: "Guinea-Bissau" },
	GY: { numeric: "328", name: "Guyana" },
	HK: { numeric: "344", name: "Hong Kong" },
	HM: { numeric: "334", name: "Heard Island and McDonald Islands" },
	HN: { numeric: "340", name: "Honduras" },
	HR: { numeric: "191", name: "Croatia" },
	HT: { numeric: "332", name: "Haiti" },
	HU: { numeric: "348", name: "Hungary" },
	ID: { numeric: "360", name: "Indonesia" },
	IE: { numeric: "372", name: "Ireland" },
	IL: { numeric: "376", name: "Israel" },
	IM: { numeric: "833", name: "Isle of Man" },
	IN: { numeric: "356", name: "India" },
	IO: { numeric: "086", name: "British Indian Ocean Territory" },
	IQ: { numeric: "368", name: "Iraq" },
	IR: { numeric: "364", name: "Iran" },
	IS: { numeric: "352", name: "Iceland" },
	IT: { numeric: "380", name: "Italy" },
	JE: { numeric: "832", name: "Jersey" },
	JM: { numeric: "388", name: "Jamaica" },
	JO: { numeric: "400", name: "Jordan" },
	JP: { numeric: "392", name: "Japan" },
	KE: { numeric: "404", name: "Kenya" },
	KG: { numeric: "417", name: "Kyrgyzstan" },
	KH: { numeric: "116", name: "Cambodia" },
	KI: { numeric: "296", name: "Kiribati" },
	KM: { numeric: "174", name: "Comoros" },
	KN: { numeric: "659", name: "Saint Kitts and Nevis" },
	KP: { numeric: "408", name: "North Korea" },
	KR: { numeric: "410", name: "South Korea" },
	KW: { numeric: "414", name: "Kuwait" },
	KY: { numeric: "136", name: "Cayman Islands" },
	KZ: { numeric: "398", name: "Kazakhstan" },
	LA: { numeric: "418", name: "Laos" },
	LB: { numeric: "422", name: "Lebanon" },
	LC: { numeric: "662", name: "Saint Lucia" },
	LI: { numeric: "438", name: "Liechtenstein" },
	LK: { numeric: "144", name: "Sri Lanka" },
	LR: { numeric: "430", name: "Liberia" },
	LS: { numeric: "426", name: "Lesotho" },
	LT: { numeric: "440", name: "Lithuania" },
	LU: { numeric: "442", name: "Luxembourg" },
	LV: { numeric: "428", name: "Latvia" },
	LY: { numeric: "434", name: "Libya" },
	MA: { numeric: "504", name: "Morocco" },
	MC: { numeric: "492", name: "Monaco" },
	MD: { numeric: "498", name: "Moldova" },
	ME: { numeric: "499", name: "Montenegro" },
	MF: { numeric: "663", name: "Saint Martin" },
	MG: { numeric: "450", name: "Madagascar" },
	MH: { numeric: "584", name: "Marshall Islands" },
	MK: { numeric: "807", name: "North Macedonia" },
	ML: { numeric: "466", name: "Mali" },
	MM: { numeric: "104", name: "Myanmar" },
	MN: { numeric: "496", name: "Mongolia" },
	MO: { numeric: "446", name: "Macao" },
	MP: { numeric: "580", name: "Northern Mariana Islands" },
	MQ: { numeric: "474", name: "Martinique" },
	MR: { numeric: "478", name: "Mauritania" },
	MS: { numeric: "500", name: "Montserrat" },
	MT: { numeric: "470", name: "Malta" },
	MU: { numeric: "480", name: "Mauritius" },
	MV: { numeric: "462", name: "Maldives" },
	MW: { numeric: "454", name: "Malawi" },
	MX: { numeric: "484", name: "Mexico" },
	MY: { numeric: "458", name: "Malaysia" },
	MZ: { numeric: "508", name: "Mozambique" },
	NA: { numeric: "516", name: "Namibia" },
	NC: { numeric: "540", name: "New Caledonia" },
	NE: { numeric: "562", name: "Niger" },
	NF: { numeric: "574", name: "Norfolk Island" },
	NG: { numeric: "566", name: "Nigeria" },
	NI: { numeric: "558", name: "Nicaragua" },
	NL: { numeric: "528", name: "Netherlands" },
	NO: { numeric: "578", name: "Norway" },
	NP: { numeric: "524", name: "Nepal" },
	NR: { numeric: "520", name: "Nauru" },
	NU: { numeric: "570", name: "Niue" },
	NZ: { numeric: "554", name: "New Zealand" },
	OM: { numeric: "512", name: "Oman" },
	PA: { numeric: "591", name: "Panama" },
	PE: { numeric: "604", name: "Peru" },
	PF: { numeric: "258", name: "French Polynesia" },
	PG: { numeric: "598", name: "Papua New Guinea" },
	PH: { numeric: "608", name: "Philippines" },
	PK: { numeric: "586", name: "Pakistan" },
	PL: { numeric: "616", name: "Poland" },
	PM: { numeric: "666", name: "Saint Pierre and Miquelon" },
	PN: { numeric: "612", name: "Pitcairn Islands" },
	PR: { numeric: "630", name: "Puerto Rico" },
	PS: { numeric: "275", name: "Palestine" },
	PT: { numeric: "620", name: "Portugal" },
	PW: { numeric: "585", name: "Palau" },
	PY: { numeric: "600", name: "Paraguay" },
	QA: { numeric: "634", name: "Qatar" },
	RE: { numeric: "638", name: "Réunion" },
	RO: { numeric: "642", name: "Romania" },
	RS: { numeric: "688", name: "Serbia" },
	RU: { numeric: "643", name: "Russia" },
	RW: { numeric: "646", name: "Rwanda" },
	SA: { numeric: "682", name: "Saudi Arabia" },
	SB: { numeric: "090", name: "Solomon Islands" },
	SC: { numeric: "690", name: "Seychelles" },
	SD: { numeric: "729", name: "Sudan" },
	SE: { numeric: "752", name: "Sweden" },
	SG: { numeric: "702", name: "Singapore" },
	SH: { numeric: "654", name: "Saint Helena" },
	SI: { numeric: "705", name: "Slovenia" },
	SJ: { numeric: "744", name: "Svalbard and Jan Mayen" },
	SK: { numeric: "703", name: "Slovakia" },
	SL: { numeric: "694", name: "Sierra Leone" },
	SM: { numeric: "674", name: "San Marino" },
	SN: { numeric: "686", name: "Senegal" },
	SO: { numeric: "706", name: "Somalia" },
	SR: { numeric: "740", name: "Suriname" },
	SS: { numeric: "728", name: "South Sudan" },
	ST: { numeric: "678", name: "São Tomé and Príncipe" },
	SV: { numeric: "222", name: "El Salvador" },
	SX: { numeric: "534", name: "Sint Maarten" },
	SY: { numeric: "760", name: "Syria" },
	SZ: { numeric: "748", name: "Eswatini" },
	TC: { numeric: "796", name: "Turks and Caicos Islands" },
	TD: { numeric: "148", name: "Chad" },
	TF: { numeric: "260", name: "French Southern Territories" },
	TG: { numeric: "768", name: "Togo" },
	TH: { numeric: "764", name: "Thailand" },
	TJ: { numeric: "762", name: "Tajikistan" },
	TL: { numeric: "626", name: "Timor-Leste" },
	TM: { numeric: "795", name: "Turkmenistan" },
	TN: { numeric: "788", name: "Tunisia" },
	TO: { numeric: "776", name: "Tonga" },
	TR: { numeric: "792", name: "Turkey" },
	TT: { numeric: "780", name: "Trinidad and Tobago" },
	TV: { numeric: "798", name: "Tuvalu" },
	TW: { numeric: "158", name: "Taiwan" },
	TZ: { numeric: "834", name: "Tanzania" },
	UA: { numeric: "804", name: "Ukraine" },
	UG: { numeric: "800", name: "Uganda" },
	UM: { numeric: "581", name: "United States Minor Outlying Islands" },
	US: { numeric: "840", name: "United States" },
	UY: { numeric: "858", name: "Uruguay" },
	UZ: { numeric: "860", name: "Uzbekistan" },
	VA: { numeric: "336", name: "Vatican City" },
	VC: { numeric: "670", name: "Saint Vincent and the Grenadines" },
	VE: { numeric: "862", name: "Venezuela" },
	VG: { numeric: "092", name: "British Virgin Islands" },
	VI: { numeric: "850", name: "United States Virgin Islands" },
	VN: { numeric: "704", name: "Vietnam" },
	VU: { numeric: "548", name: "Vanuatu" },
	WF: { numeric: "876", name: "Wallis and Futuna" },
	WS: { numeric: "882", name: "Samoa" },
	XK: { numeric: "", name: "Kosovo" },
	YE: { numeric: "887", name: "Yemen" },
	YT: { numeric: "175", name: "Mayotte" },
	ZA: { numeric: "710", name: "South Africa" },
	ZM: { numeric: "894", name: "Zambia" },
	ZW: { numeric: "716", name: "Zimbabwe" },
};

/** Codes with no ISO numeric equivalent (user-assigned or sub-entities). */
const NO_NUMERIC = new Set(["AC", "XK", "CP", "TA"]);

/** Look up a country by ISO 3166-1 alpha-2 code. */
export function isoCountry(
	alpha2: string | null | undefined,
): IsoCountry | null {
	if (!alpha2) return null;
	return ISO_COUNTRIES[alpha2.toUpperCase()] ?? null;
}

/** ISO numeric id for shading world-atlas features; null when unmappable. */
export function isoNumeric(alpha2: string | null | undefined): string | null {
	const c = isoCountry(alpha2);
	if (!c || c.numeric === "" || NO_NUMERIC.has(alpha2?.toUpperCase() ?? "")) {
		return null;
	}
	return c.numeric;
}
